// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#ifndef _MAD_STARTUP_SQ_UI_H
#define _MAD_STARTUP_SQ_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "sq_ui/sq_ui_helpers.h"
#include "sq_ui/components/ui_comp.h"
#include "sq_ui/components/ui_comp_hook.h"
#include "sq_ui/sq_ui_events.h"


///////////////////// SCREENS ////////////////////

#include "sq_ui/screens/ui_Splash.h"
#include "sq_ui/screens/ui_Clock.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * upanim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * hour_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * min_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * sec_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * bannerfading_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_mad_logo_png);    // assets/mad_logo.png

// FONTS
LV_FONT_DECLARE(ui_font_Number);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
