// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#include "sq_ui/sq_ui.h"

lv_obj_t * ui_Clock = NULL;
lv_obj_t * ui_Date = NULL;
lv_obj_t * ui_Spinner1 = NULL;

static void _clock_set_opa(void * obj, int32_t v) { lv_obj_set_style_opa((lv_obj_t *)obj, (lv_opa_t)v, LV_PART_MAIN); }
void ui_event_Clock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        /* Safe animation: fade-in only (no negative Y) */
        if(ui_Date) {
            lv_obj_set_style_opa(ui_Date, 0, LV_PART_MAIN);
            lv_anim_t a;
            lv_anim_init(&a);
            lv_anim_set_var(&a, ui_Date);
            lv_anim_set_exec_cb(&a, _clock_set_opa);
            lv_anim_set_values(&a, 0, 255);
            lv_anim_set_time(&a, 350);
            lv_anim_set_delay(&a, 120);
            lv_anim_start(&a);
        }
    }
}

// build funtions

void ui_Clock_screen_init(void)
{
    ui_Clock = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Clock, lv_color_hex(0x333232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_Clock, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = ui_Small_Label_create(ui_Clock);
    lv_obj_align_to(ui_Date, ui_Spinner1, LV_ALIGN_OUT_TOP_MID, 0, -25);
    lv_label_set_text(ui_Date, "Preparing System ...");
    lv_obj_set_style_text_color(ui_Date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    /* Remove transform scaling; use a real font size for clarity */
#if LV_FONT_MONTSERRAT_28
    lv_obj_set_style_text_font(ui_Date, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
#elif LV_FONT_MONTSERRAT_24
    lv_obj_set_style_text_font(ui_Date, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
#endif

    ui_Spinner1 = lv_spinner_create(ui_Clock);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 150);
    lv_obj_set_height(ui_Spinner1, 150);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x5B8EE4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Clock, ui_event_Clock, LV_EVENT_ALL, NULL);

}

void ui_Clock_screen_destroy(void)
{
    if(ui_Clock) lv_obj_del(ui_Clock);

    // NULL screen variables
    ui_Clock = NULL;
    ui_Date = NULL;
    ui_Spinner1 = NULL;

}
