// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#include "sq_ui/sq_ui.h"

lv_obj_t * ui_Splash = NULL;
lv_obj_t * ui_Startup_H1 = NULL;
lv_obj_t * ui_MAD_logo = NULL;
// event funtions
void ui_event_Splash(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_MAD_logo, 100);
        upanim_Animation(ui_Startup_H1, 100);
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1400, &ui_Clock_screen_init);
    }
}

// build funtions

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Splash, lv_color_hex(0x333232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Startup_H1 = ui_Small_Label_create(ui_Splash);
    lv_obj_set_x(ui_Startup_H1, -5);
    lv_obj_set_y(ui_Startup_H1, 67);
    lv_obj_set_align(ui_Startup_H1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Startup_H1, "Embedded Device");
    lv_obj_set_style_text_color(ui_Startup_H1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Startup_H1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MAD_logo = lv_image_create(ui_Splash);
    lv_image_set_src(ui_MAD_logo, &ui_img_mad_logo_png);
    lv_obj_set_width(ui_MAD_logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MAD_logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MAD_logo, -2);
    lv_obj_set_y(ui_MAD_logo, -59);
    lv_obj_set_align(ui_MAD_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MAD_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_MAD_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_MAD_logo, 250);

    lv_obj_add_event_cb(ui_Splash, ui_event_Splash, LV_EVENT_ALL, NULL);

}

void ui_Splash_screen_destroy(void)
{
    if(ui_Splash) lv_obj_del(ui_Splash);

    // NULL screen variables
    ui_Splash = NULL;
    ui_Startup_H1 = NULL;
    ui_MAD_logo = NULL;

}
